export const RECEIVE_SURVEYS = 'RECEIVE_SURVEYS';
export const CHOOSE_SURVEY = 'CHOOSE_SURVEY';
export const CHOOSE_QUESTION = 'CHOOSE_QUESTION'
export const CHOOSE_ANSWER = 'CHOOSE_ANSWER';
export const SUBMIT_ANSWERS = 'SUBMIT_ANSWERS';
